### ISSUE TITLE
Missing watch directory causes ungraceful abort

### ISSUE THREAD

**Issue by vsnine** [PhracturedBlue/asterisk_mbox_server#1]
Hello,

I attempted to set this up today and found that if one of the hard-coded watch directories in the mailbox doesn't exist, the script aborts rather ungracefully.

[root@freepbx1 ~]# sudo -u asterisk  /usr/local/bin/asterisk_mbox_server -v --cfg /etc/asterisk/asterisk_mbox.ini
DEBUG:inotify.adapters:Inotify handle is (7).
DEBUG:root:Watching Directory: /var/spool/asterisk/voicemail/default/101/INBOX
DEBUG:inotify.adapters:Adding watch: [b'/var/spool/asterisk/voicemail/default/101/INBOX']
DEBUG:inotify.adapters:Added watch (1): [b'/var/spool/asterisk/voicemail/default/101/INBOX']
DEBUG:root:Watching Directory: /var/spool/asterisk/voicemail/default/101/Old
DEBUG:inotify.adapters:Adding watch: [b'/var/spool/asterisk/voicemail/default/101/Old']
Traceback (most recent call last):
  File "/usr/local/bin/asterisk_mbox_server", line 3, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/asterisk_mbox_server/__init__.py", line 330, in main
    {'GOOGLE_KEY': opts['google_key']})
  File "/usr/lib/python3.6/site-packages/asterisk_mbox_server/__init__.py", line 178, in __init__
    self.inot.add_watch(directory.encode('utf-8'))
  File "/usr/lib/python3.6/site-packages/inotify/adapters.py", line 67, in add_watch
    wd = inotify.calls.inotify_add_watch(self.__inotify_fd, path, mask)
  File "/usr/lib/python3.6/site-packages/inotify/calls.py", line 35, in _check_nonnegative
    (result,))
inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)
DEBUG:inotify.adapters:Cleaning-up inotify.
[root@freepbx1 ~]#

In my case the directories Old and Urgent did not exist, so creating them allowed the script to start up.

[root@freepbx1 ~]# ll /var/spool/asterisk/voicemail/default/101
total 0
drwxrwxr-x 2 asterisk asterisk 6 Aug 26 13:14 INBOX
drwxrwxr-x 2 asterisk asterisk 6 Aug 26 13:14 tmp
[root@freepbx1 ~]# sudo -u asterisk mkdir  /var/spool/asterisk/voicemail/default/101/Urgent
[root@freepbx1 ~]# sudo -u asterisk mkdir  /var/spool/asterisk/voicemail/default/101/Old

[root@freepbx1 ~]# sudo -u asterisk  /usr/local/bin/asterisk_mbox_server -v --cfg /etc/asterisk/asterisk_mbox.ini
DEBUG:inotify.adapters:Inotify handle is (7).
DEBUG:root:Watching Directory: /var/spool/asterisk/voicemail/default/101/INBOX
DEBUG:inotify.adapters:Adding watch: [b'/var/spool/asterisk/voicemail/default/101/INBOX']
DEBUG:inotify.adapters:Added watch (1): [b'/var/spool/asterisk/voicemail/default/101/INBOX']
DEBUG:root:Watching Directory: /var/spool/asterisk/voicemail/default/101/Old
DEBUG:inotify.adapters:Adding watch: [b'/var/spool/asterisk/voicemail/default/101/Old']
DEBUG:inotify.adapters:Added watch (2): [b'/var/spool/asterisk/voicemail/default/101/Old']
DEBUG:root:Watching Directory: /var/spool/asterisk/voicemail/default/101/Urgent
DEBUG:inotify.adapters:Adding watch: [b'/var/spool/asterisk/voicemail/default/101/Urgent']
DEBUG:inotify.adapters:Added watch (3): [b'/var/spool/asterisk/voicemail/default/101/Urgent']
DEBUG:root:Reading: /var/spool/asterisk/voicemail/default/101/INBOX
DEBUG:root:Reading: /var/spool/asterisk/voicemail/default/101/Old
DEBUG:root:Reading: /var/spool/asterisk/voicemail/default/101/Urgent

**Comment by PhracturedBlue** [comment]
Thanks.  I've put in a temporary fix now.  I should probably either let the user specify them, or just search all of them in the future.  But for now it shouldn't crash anymore.
